version: "3.3"
services:

  movement_registration_service:
    build:
      context: ./MovementSystem/MovementRegistrationService/
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"



#Rabbit mq
  rabbit_node_1:
    environment:
      - RABBITMQ_ERLANG_COOKIE='7mG7R9HRDAkjfUT3kNCq5KsgVEgbTYR'
    networks:
      - rabbit
    hostname: rabbit_node_1
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    tty: true
    volumes:
      - rabbit1:/var/lib/rabbitmq
      - ./conf/:/etc/rabbitmq/
    command:  bash -c "sleep 10; rabbitmq-server;"
  rabbit_node_2:
    environment:
      - RABBITMQ_ERLANG_COOKIE='7mG7R9HRDAkjfUT3kNCq5KsgVEgbTYR'
    networks:
      - rabbit
    hostname: rabbit_node_2
    depends_on:
      - rabbit_node_1
    image: "rabbitmq:3-management"
    ports:
      - "15673:15672"
      - "5673:5672"
    tty: true
    volumes:
      - rabbit2:/var/lib/rabbitmq
      - ./conf/:/etc/rabbitmq/
    command:  bash -c "sleep 10; rabbitmq-server; "
volumes:
  rabbit1:
    driver: local
  rabbit2:
    driver: local

networks:
  rabbit: