FROM ubuntu as convert


RUN apt-get update && apt-get install -y dos2unix && apt-get install -y curl && curl -L -o mysql.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.jar

COPY domain_dev.xml domain_dev.xml
COPY ./startInForeground.sh startInForeground.sh

RUN dos2unix domain_dev.xml && dos2unix startInForeground.sh

FROM payara/server-full as run


ENV PAYARA_ARGS="-d"
EXPOSE 9009
EXPOSE 8080
EXPOSE 4848

COPY --from=convert  domain_dev.xml /opt/payara/appserver/glassfish/domains/production/config/domain.xml
COPY --from=convert --chown=payara:payara ./startInForeground.sh ${SCRIPT_DIR}/startInForeground.sh
COPY --from=convert --chown=payara:payara mysql.jar /opt/payara/appserver/glassfish/domains/production/lib/mysql-connector-java-5.1.34.jar
RUN chmod 777 ${SCRIPT_DIR}/startInForeground.sh

COPY target/Rekeningrijden.war /opt/payara/deployments/deploy.war
