FROM payara/server-full
COPY domain_dev.xml /opt/payara/appserver/glassfish/domains/production/config/domain.xml
RUN curl -L -o /opt/payara/appserver/glassfish/domains/production/lib/mysql-connector-java-5.1.34.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.jar
COPY target/Rekeningrijden.war /opt/payara/deployments/deploy.war
EXPOSE 8080
EXPOSE 4848